apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "k8s-example.database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "k8s-example.database.selectorLabels" . | nindent 4 }}