# Development environment values
global:
  namespace: k8s-example-dev
  imagePullPolicy: IfNotPresent

# Reduced resources for development
database:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

backend:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "100m"
  hpa:
    enabled: false

frontend:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"

# Development-specific configuration
config:
  frontend:
    backendUrl: "http://api.k8s-example-dev.local"

ingress:
  hosts:
    - host: k8s-example-dev.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
    - host: api.k8s-example-dev.local
      paths:
        - path: /
          pathType: Prefix
          service: backend