# Production environment values
global:
  namespace: k8s-example-prod
  imagePullPolicy: IfNotPresent

# Production resources
database:
  replicas: 1
  storage:
    size: 20Gi
    storageClass: "fast-ssd"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

backend:
  replicas: 3
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 20
    targetCPUUtilizationPercentage: 70

frontend:
  replicas: 3
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Production-specific configuration
config:
  frontend:
    backendUrl: "https://api.k8s-example.com"

ingress:
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
  hosts:
    - host: k8s-example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
    - host: api.k8s-example.com
      paths:
        - path: /
          pathType: Prefix
          service: backend
  tls:
    - secretName: k8s-example-prod-tls
      hosts:
        - k8s-example.com
        - api.k8s-example.com