apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: k8s-example
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  type: ClusterIP