apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "k8s-example.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "k8s-example.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-example.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: fastapi
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.probes.livenessProbe.path }}
            port: {{ .Values.backend.service.targetPort }}
          initialDelaySeconds: {{ .Values.backend.probes.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.probes.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.probes.readinessProbe.path }}
            port: {{ .Values.backend.service.targetPort }}
          initialDelaySeconds: {{ .Values.backend.probes.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.probes.readinessProbe.periodSeconds }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}