apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- database/deployment.yaml
- database/service.yaml
- database/pvc.yaml
- backend/deployment.yaml
- backend/service.yaml
- backend/hpa.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- frontend/ingress.yaml