apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: k8s-example
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP