apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-example-dev
  namespace: argocd
  labels:
    environment: development
    project: k8s-example
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-example

  source:
    repoURL: https://github.com/your-org/k8s-example
    targetRevision: develop
    path: helm/k8s-example
    helm:
      valueFiles:
      - values.yaml
      - values-dev.yaml
      parameters:
      - name: database.image.tag
        value: develop
      - name: backend.image.tag
        value: develop
      - name: frontend.image.tag
        value: develop

  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-example-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health check configuration
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas

  # Notification configuration
  revisionHistoryLimit: 10